theme: jekyll-theme-minimal
title: Music For Memories
description: A website to generate musical patterns to help improve patient experience. Start listening to patterns that resemble your favorite songs uninterrupted!
